### ISSUE TITLE
Errors compiling

### ISSUE THREAD

**Issue by pkkrusty** [Jojo-A/MQTT-CAN-Gateway#1]
Trying to compile the sketch gives
```
error: 'mcp2515_can' does not name a type
   78 | mcp2515_can CAN(CAN_CS_PIN);
``` 
among other errors. I assume it's a problem with having correct libraries installed. However, I installed all recommended libraries:
```
ArduinoJson
PubSubClient
WiFiManager
CAN-BUS Shield
```
In the code, it includes the mcp_can.h library and the mcp2515_can.h library. I found [mcp_can.h](https://github.com/coryjfowler/MCP_CAN_lib) and [mcp2515_can.h](https://github.com/Seeed-Studio/Seeed_Arduino_CAN)

Any ideas?

**Comment by pkkrusty** [comment]
Ah figured it out. Conflicting libraries, I shouldn't have installed the coryfowler mcp_can library.

**Comment by Jojo-A** [comment]
> Ah figured it out. Conflicting libraries, I shouldn't have installed the coryfowler mcp_can library.

Hey,
Cool that you are interested in this project :) .
And even better to see that you have figured out where the problem was! On the other hand this tells me that my description should be more detailed.

Let me know if you have more problems or other Input!

Greetings

**Comment by pkkrusty** [comment]
Ultimate goal is to get a generic Canbus driver incorporated into the Tasmota project, but this is a good first step.

**Comment by Jojo-A** [comment]
> Ultimate goal is to get a generic Canbus driver incorporated into the Tasmota project, but this is a good first step.

That sounds awesome! I would be glad to see this idea and maybe part of my code merged into projects like Tasmota!
My main goal was to convince the Home Assistant devs to implement a generic CAN bus support into Home Assistant so that the detour through ethernet/MQTT could be avoided. But no success. There is just not enough community support and the devs say that it would be easier to implement CAN support into projects like Tasmota or ESPhome but into Home Assistant. So this MQTT-to-CAN gateway was just my "workaround" for the lag of CAN support in Home Assistant...
